In [1]:
import pandas as pd

In [2]:
la = pd.read_csv(r"C:\Users\Lenovo\Downloads\Port_of_Los_Angeles_-_TEU_Counts_Monthly_And_Calendar_YTD.csv")

In [3]:
la.head()

,Month-Year,Date,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD
0,Jan-09,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN
1,Feb-09,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN
2,Mar-09,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN
3,Apr-09,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN
4,May-09,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN

In [4]:
export_constant_US = pd.read_excel(r"C:\Users\Lenovo\Downloads\Exports Merchandise, Customs, constant 2010 US$, millions, seas. adj..xlsx",sheet_name='monthly')

In [5]:
export_constant_US.columns

Index(['Date', 'Advanced Economies', 'Argentina', 'Australia', 'Belgium',
       'Brazil', 'Canada', 'Chile', 'China', 'Czech Republic', 'Germany',
       'Denmark', 'EMDE East Asia & Pacific', 'EMDE Europe & Central Asia',
       'Emerging Market and Developing Economies (EMDEs)', 'Spain', 'Estonia',
       'Finland', 'France', 'United Kingdom', 'High Income Countries',
       'Hong Kong SAR, China', 'Hungary', 'Indonesia', 'Ireland', 'Israel',
       'Italy', 'Jordan', 'Japan', 'Korea, Rep.',
       'EMDE Latin America & Caribbean', 'Low-Income Countries (LIC)',
       'Mexico', 'Middle-Income Countries (MIC)',
       'EMDE Middle East, North Africa, Afghanistan & Pakistan', 'Malaysia',
       'Netherlands', 'Peru', 'Philippines', 'Poland', 'Russian Federation',
       'EMDE South Asia', 'Singapore', 'EMDE Sub-Saharan Africa', 'Slovakia',
       'Sweden', 'Thailand', 'Turkey', 'Taiwan, China', 'Uganda',
       'United States', 'World (WBG members)', 'South Africa'],
      dtype='object')

In [6]:
Export_constant_us = export_constant_US[['Date','United States']]

In [7]:
export_current_US = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Exports Merchandise, Customs, current US$, millions, seas. adj. (1).xlsx",sheet_name='monthly')

In [8]:
export_current_US.columns

Index(['Date', 'Angola', 'Albania', 'Advanced Economies', 'Argentina',
       'Australia', 'Austria', 'Azerbaijan', 'Burundi', 'Belgium',
       ...
       'Uganda', 'Ukraine', 'Uruguay', 'United States', 'Venezuela, RB',
       'Viet Nam', 'World (WBG members)', 'Samoa', 'South Africa', 'Zambia'],
      dtype='object', length=139)

In [20]:
Export_current_us = export_current_US[['Date','United States']]

In [21]:
Export_current_us

        Date  United States
0    1995M12        50832.0
1    1996M01        50275.0
2    1996M02        51625.0
3    1996M03        50901.0
4    1996M04        51351.0
..       ...            ...
355  2025M07       178370.5
356  2025M08       176074.2
357  2025M09            NaN
358  2025M10            NaN
359  2025M11            NaN

[360 rows x 2 columns]

In [22]:
import_constant_US = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Imports Merchandise, Customs, constant 2010 US$, millions, seas. adj. (1).xlsx",sheet_name='monthly')

In [23]:
import_constant_US.head()

,Date,Advanced Economies,Argentina,Australia,Austria,Belgium,Bulgaria,Brazil,Canada,Chile,...,Singapore,EMDE Sub-Saharan Africa,Slovakia,Thailand,Turkey,"Taiwan, China",United States,Viet Nam,World (WBG members),South Africa
0,1995M12,394980.6,NaN,5636.000,NaN,25245.82,NaN,4871.923,NaN,NaN,...,11489.90,NaN,NaN,9269.842,180.1500,9633.271,78338.04,629.2726,NaN,NaN
1,1996M01,420443.9,NaN,6203.912,NaN,27627.69,NaN,5450.978,NaN,NaN,...,12221.02,NaN,NaN,9069.119,202.9189,10636.140,82712.50,683.7402,NaN,NaN
2,1996M02,421230.3,NaN,6385.003,NaN,27839.04,NaN,5284.290,NaN,NaN,...,12218.50,NaN,NaN,8524.506,210.3674,10558.320,83416.95,790.1343,524297.0,NaN
3,1996M03,395701.4,NaN,5492.365,NaN,26457.56,NaN,5252.052,NaN,NaN,...,12129.92,NaN,NaN,7991.000,250.4447,8965.276,77168.70,658.0304,493584.7,NaN
4,1996M04,415908.3,NaN,6363.270,NaN,27953.25,NaN,5949.824,NaN,NaN,...,12120.44,NaN,NaN,8324.549,277.8170,10448.810,81622.97,702.7437,519476.6,NaN

In [24]:
Import_constant_us = import_constant_US[['Date','United States']]

In [25]:
import_current_US = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Imports Merchandise, Customs, current US$, millions, seas. adj. (1).xlsx",sheet_name='monthly')

In [27]:
import_constant_US.head()

,Date,Advanced Economies,Argentina,Australia,Austria,Belgium,Bulgaria,Brazil,Canada,Chile,...,Singapore,EMDE Sub-Saharan Africa,Slovakia,Thailand,Turkey,"Taiwan, China",United States,Viet Nam,World (WBG members),South Africa
0,1995M12,394980.6,NaN,5636.000,NaN,25245.82,NaN,4871.923,NaN,NaN,...,11489.90,NaN,NaN,9269.842,180.1500,9633.271,78338.04,629.2726,NaN,NaN
1,1996M01,420443.9,NaN,6203.912,NaN,27627.69,NaN,5450.978,NaN,NaN,...,12221.02,NaN,NaN,9069.119,202.9189,10636.140,82712.50,683.7402,NaN,NaN
2,1996M02,421230.3,NaN,6385.003,NaN,27839.04,NaN,5284.290,NaN,NaN,...,12218.50,NaN,NaN,8524.506,210.3674,10558.320,83416.95,790.1343,524297.0,NaN
3,1996M03,395701.4,NaN,5492.365,NaN,26457.56,NaN,5252.052,NaN,NaN,...,12129.92,NaN,NaN,7991.000,250.4447,8965.276,77168.70,658.0304,493584.7,NaN
4,1996M04,415908.3,NaN,6363.270,NaN,27953.25,NaN,5949.824,NaN,NaN,...,12120.44,NaN,NaN,8324.549,277.8170,10448.810,81622.97,702.7437,519476.6,NaN

In [28]:
Import_current_us = import_current_US[['Date','United States']]

In [29]:
industry = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Industrial Production, constant 2010 US$, seas. adj. (1).xlsx",sheet_name='monthly')

In [30]:
industry.head()

,Date,Advanced Economies,Austria,Belgium,Bangladesh,Bulgaria,Bosnia and Herzegovina,Belarus,Brazil,Barbados,...,Tunisia,Turkey,Uganda,Ukraine,Uruguay,United States,Uzbekistan,Viet Nam,World (WBG members),South Africa
0,1996M01,6.300000e+11,5.310000e+09,5.060000e+09,NaN,NaN,NaN,NaN,2.910000e+10,36812021.0,...,742000000.0,9.700000e+09,NaN,NaN,NaN,1.970000e+11,NaN,NaN,8.690000e+11,7.550000e+09
1,1996M02,6.330000e+11,5.150000e+09,4.940000e+09,NaN,NaN,NaN,NaN,3.030000e+10,37407804.0,...,720000000.0,9.030000e+09,NaN,NaN,NaN,2.000000e+11,NaN,NaN,8.690000e+11,7.530000e+09
2,1996M03,6.310000e+11,5.180000e+09,5.010000e+09,NaN,NaN,NaN,NaN,2.900000e+10,35817555.0,...,756000000.0,9.060000e+09,NaN,NaN,NaN,1.990000e+11,NaN,NaN,8.680000e+11,7.560000e+09
3,1996M04,6.340000e+11,5.050000e+09,5.070000e+09,NaN,NaN,NaN,NaN,2.860000e+10,34517272.0,...,748000000.0,9.450000e+09,NaN,NaN,NaN,2.010000e+11,NaN,NaN,8.720000e+11,7.770000e+09
4,1996M05,6.380000e+11,5.230000e+09,5.050000e+09,NaN,NaN,NaN,NaN,3.040000e+10,36672711.0,...,756000000.0,9.370000e+09,NaN,NaN,NaN,2.030000e+11,NaN,NaN,8.790000e+11,7.900000e+09

In [31]:
Industry = industry[['Date','United States']]

In [32]:
exchange = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Official exchange rate, LCU per USD, period average (1).xlsx",sheet_name='monthly')

In [33]:
exchange.head()

,Date,Aruba,Afghanistan,Angola,Albania,Netherlands Antilles,United Arab Emirates,Argentina,Armenia,Antigua and Barbuda,...,"Venezuela, RB","Virgin Islands, U.S.",Viet Nam,Vanuatu,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
0,1996M01,1.788196,47.5,5692.00,95.49209,1.775870,3.672348,1.000826,402.01,2.7,...,0.287979,1.0,11000.26,113.8243,2.515842,NaN,12.0,3.640696,0.958522,NaN
1,1996M02,1.785190,47.5,5692.00,99.89610,1.775714,3.672667,1.000714,402.53,2.7,...,0.288975,1.0,11005.90,112.6281,2.491358,NaN,12.0,3.747190,1.000286,NaN
2,1996M03,1.788952,47.5,26816.48,99.84114,1.775524,3.672667,1.000190,403.30,2.7,...,0.288975,1.0,11009.83,112.1298,2.459444,NaN,12.0,3.927524,1.099095,NaN
3,1996M04,1.789136,47.5,31784.00,99.51955,1.775386,3.672227,1.000000,405.48,2.7,...,0.359724,1.0,10998.66,111.2768,2.446793,NaN,12.0,4.209409,1.198318,NaN
4,1996M05,1.789565,47.5,31784.00,99.33935,1.776348,3.672348,1.000000,406.58,2.7,...,0.467343,1.0,10990.39,110.5989,2.540775,NaN,12.0,4.366217,1.213804,NaN

In [34]:
Exchange = exchange[['Date','United States']]

In [35]:
retail_market = pd.read_excel(r"C:\Users\Lenovo\Downloads\Thesis Datasets\Retail Sales Volume Index, seas. adj. (1).xlsx",sheet_name='monthly')

In [36]:
retail_market.head()

,Date,Advanced Economies,Belgium,Brazil,Canada,Switzerland,Czech Republic,Germany,Denmark,EMDE East Asia & Pacific,...,Romania,EMDE South Asia,Singapore,EMDE Sub-Saharan Africa,Slovenia,Sweden,Turkey,United States,World (WBG members),South Africa
0,1996M01,62.38740,72.12050,NaN,NaN,NaN,NaN,102.57620,NaN,NaN,...,NaN,NaN,48.55648,NaN,NaN,57.19563,NaN,82.17274,64.36588,NaN
1,1996M02,63.20339,74.53086,NaN,NaN,NaN,NaN,102.36540,NaN,NaN,...,NaN,NaN,51.16705,NaN,NaN,57.63003,NaN,83.25437,64.95100,NaN
2,1996M03,62.75838,72.02511,NaN,NaN,NaN,NaN,102.04910,NaN,NaN,...,NaN,NaN,49.39186,NaN,NaN,57.63003,NaN,83.29741,64.61426,NaN
3,1996M04,62.50773,70.76236,NaN,NaN,NaN,NaN,101.38070,NaN,NaN,...,NaN,NaN,49.25188,NaN,NaN,58.18663,NaN,83.63425,64.38045,NaN
4,1996M05,62.34340,71.12046,NaN,NaN,NaN,NaN,99.83993,NaN,NaN,...,NaN,NaN,49.25188,NaN,NaN,58.18663,NaN,84.21686,64.26714,NaN

In [37]:
Retails = retail_market[['Date','United States']]

In [38]:
df = Export_constant_us.copy()

In [39]:
df.head()

      Date  United States
0      NaN            NaN
1  1995M12       58903.76
2  1996M01       58081.94
3  1996M02       59779.40
4  1996M03       59047.29

In [40]:
df = pd.merge(df,Export_current_us,on='Date',suffixes=('_export_constant_us','_export_current_us'))

In [41]:
df = pd.merge(df,Import_constant_us,on='Date')

In [42]:
df = pd.merge(df,Import_current_us,on='Date',suffixes=('_import_constant_us','_import_current_us'))

In [43]:
df

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us
0,1995M12,58903.76,50832.0,78338.04,61739.44
1,1996M01,58081.94,50275.0,82712.50,65510.37
2,1996M02,59779.40,51625.0,83416.95,66068.31
3,1996M03,59047.29,50901.0,77168.70,61481.55
4,1996M04,59279.46,51351.0,81622.97,65540.88
...,...,...,...,...,...
355,2025M07,141898.40,178370.5,261601.30,287577.30
356,2025M08,139476.00,176074.2,232828.70,257040.00
357,2025M09,NaN,NaN,NaN,NaN
358,2025M10,NaN,NaN,NaN,NaN
359,2025M11,NaN,NaN,NaN,NaN

In [44]:
df = pd.merge(df,Industry,on='Date')

In [45]:
df

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States
0,1996M01,58081.94,50275.0,82712.50,65510.37,1.970000e+11
1,1996M02,59779.40,51625.0,83416.95,66068.31,2.000000e+11
2,1996M03,59047.29,50901.0,77168.70,61481.55,1.990000e+11
3,1996M04,59279.46,51351.0,81622.97,65540.88,2.010000e+11
4,1996M05,59908.04,52012.0,84402.00,67046.47,2.030000e+11
...,...,...,...,...,...,...
354,2025M07,141898.40,178370.5,261601.30,287577.30,2.750000e+11
355,2025M08,139476.00,176074.2,232828.70,257040.00,2.750000e+11
356,2025M09,NaN,NaN,NaN,NaN,2.750000e+11
357,2025M10,NaN,NaN,NaN,NaN,NaN
358,2025M11,NaN,NaN,NaN,NaN,NaN

In [46]:
df = pd.merge(df,Exchange,on='Date',suffixes=('_Industry_production','_Exchange_rate'))

In [47]:
df

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate
0,1996M01,58081.94,50275.0,82712.50,65510.37,1.970000e+11,1
1,1996M02,59779.40,51625.0,83416.95,66068.31,2.000000e+11,1
2,1996M03,59047.29,50901.0,77168.70,61481.55,1.990000e+11,1
3,1996M04,59279.46,51351.0,81622.97,65540.88,2.010000e+11,1
4,1996M05,59908.04,52012.0,84402.00,67046.47,2.030000e+11,1
...,...,...,...,...,...,...,...
354,2025M07,141898.40,178370.5,261601.30,287577.30,2.750000e+11,1
355,2025M08,139476.00,176074.2,232828.70,257040.00,2.750000e+11,1
356,2025M09,NaN,NaN,NaN,NaN,2.750000e+11,1
357,2025M10,NaN,NaN,NaN,NaN,NaN,1
358,2025M11,NaN,NaN,NaN,NaN,NaN,1

In [48]:
df = pd.merge(df,Retails,on='Date')

In [49]:
df.rename(columns={'United States':'Retail_market'},inplace=True)

In [50]:
df

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate,Retail_market
0,1996M01,58081.94,50275.0,82712.50,65510.37,1.970000e+11,1,82.17274
1,1996M02,59779.40,51625.0,83416.95,66068.31,2.000000e+11,1,83.25437
2,1996M03,59047.29,50901.0,77168.70,61481.55,1.990000e+11,1,83.29741
3,1996M04,59279.46,51351.0,81622.97,65540.88,2.010000e+11,1,83.63425
4,1996M05,59908.04,52012.0,84402.00,67046.47,2.030000e+11,1,84.21686
...,...,...,...,...,...,...,...,...
354,2025M07,141898.40,178370.5,261601.30,287577.30,2.750000e+11,1,140.91760
355,2025M08,139476.00,176074.2,232828.70,257040.00,2.750000e+11,1,141.21640
356,2025M09,NaN,NaN,NaN,NaN,2.750000e+11,1,141.00930
357,2025M10,NaN,NaN,NaN,NaN,NaN,1,NaN
358,2025M11,NaN,NaN,NaN,NaN,NaN,1,NaN

In [51]:
la

,Month-Year,Date,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD
0,Jan-09,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN
1,Feb-09,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN
2,Mar-09,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN
3,Apr-09,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN
4,May-09,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN
...,...,...,...,...,...,...
88,Feb-16,02/29/2016 12:00:00 AM,713721.00,NaN,NaN,NaN
89,Mar-16,03/31/2016 12:00:00 AM,612863.20,NaN,NaN,NaN
90,Jun-16,06/30/2016 12:00:00 AM,676006.90,NaN,NaN,NaN
91,Sep-16,09/30/2016 12:00:00 AM,747707.40,NaN,NaN,NaN
92,Aug-16,08/31/2016 12:00:00 AM,798932.75,NaN,NaN,NaN

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               359 non-null    object
 1   United States_export_constant_us   356 non-null    float64
 2   United States_export_current_us    356 non-null    float64
 3   United States_import_constant_us   356 non-null    float64
 4   United States_import_current_us    356 non-null    float64
 5   United States_Industry_production  357 non-null    float64
 6   United States_Exchange_rate        359 non-null    int64
 7   Retail_market                      357 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 22.6+ KB

In [53]:
df['Date'] = pd.to_datetime(df['Date'],format='%YM%m')

In [54]:
df.head()

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate,Retail_market
0,1996-01-01,58081.94,50275.0,82712.50,65510.37,1.970000e+11,1,82.17274
1,1996-02-01,59779.40,51625.0,83416.95,66068.31,2.000000e+11,1,83.25437
2,1996-03-01,59047.29,50901.0,77168.70,61481.55,1.990000e+11,1,83.29741
3,1996-04-01,59279.46,51351.0,81622.97,65540.88,2.010000e+11,1,83.63425
4,1996-05-01,59908.04,52012.0,84402.00,67046.47,2.030000e+11,1,84.21686

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               359 non-null    datetime64[ns]
 1   United States_export_constant_us   356 non-null    float64
 2   United States_export_current_us    356 non-null    float64
 3   United States_import_constant_us   356 non-null    float64
 4   United States_import_current_us    356 non-null    float64
 5   United States_Industry_production  357 non-null    float64
 6   United States_Exchange_rate        359 non-null    int64
 7   Retail_market                      357 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 22.6 KB

In [56]:
df['Date']

0     1996-01-01
1     1996-02-01
2     1996-03-01
3     1996-04-01
4     1996-05-01
         ...
354   2025-07-01
355   2025-08-01
356   2025-09-01
357   2025-10-01
358   2025-11-01
Name: Date, Length: 359, dtype: datetime64[ns]

In [57]:
df[(df['Date']<='1996-12-31') & (df['Date'] >= '1996-01-01')]

,Date,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate,Retail_market
0,1996-01-01,58081.94,50275.0,82712.50,65510.37,1.970000e+11,1,82.17274
1,1996-02-01,59779.40,51625.0,83416.95,66068.31,2.000000e+11,1,83.25437
2,1996-03-01,59047.29,50901.0,77168.70,61481.55,1.990000e+11,1,83.29741
3,1996-04-01,59279.46,51351.0,81622.97,65540.88,2.010000e+11,1,83.63425
4,1996-05-01,59908.04,52012.0,84402.00,67046.47,2.030000e+11,1,84.21686
5,1996-06-01,60055.19,52114.0,79777.18,62873.65,2.040000e+11,1,83.38537
6,1996-07-01,59354.82,51330.0,85269.35,67268.79,2.050000e+11,1,83.76400
7,1996-08-01,60804.15,52521.0,84968.98,67031.82,2.060000e+11,1,83.66482
8,1996-09-01,60817.36,52264.0,84054.95,66836.50,2.070000e+11,1,84.34349
9,1996-10-01,62390.96,53474.0,86110.32,68605.49,2.070000e+11,1,84.98099
10,1996-11-01,63451.92,54123.0,84562.97,67372.69,2.090000e+11,1,84.57242
11,1996-12-01,62247.81,53087.0,87281.89,69811.87,2.100000e+11,1,84.56493

In [58]:
pd.Timestamp.today()

Timestamp('2026-02-17 15:56:18.949709')

In [59]:
df['Date'].dt.day_name()

0         Monday
1       Thursday
2         Friday
3         Monday
4      Wednesday
         ...
354      Tuesday
355       Friday
356       Monday
357    Wednesday
358     Saturday
Name: Date, Length: 359, dtype: object

In [60]:
df.loc[df.shape[0]-1,'Date'] - df.loc[0,'Date']

Timedelta('10897 days 00:00:00')

In [61]:
la.head()

,Month-Year,Date,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD
0,Jan-09,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN
1,Feb-09,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN
2,Mar-09,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN
3,Apr-09,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN
4,May-09,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN

In [62]:
la['Month-Year'] = pd.to_datetime(la['Month-Year'],format = '%b-%y')

In [63]:
la.head()

,Month-Year,Date,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD
0,2009-01-01,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN
1,2009-02-01,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN
2,2009-03-01,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN
3,2009-04-01,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN
4,2009-05-01,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN

In [64]:
final_df = pd.merge(la,df,left_on='Month-Year',right_on='Date')

In [65]:
final_df

,Month-Year,Date_x,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD,Date_y,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate,Retail_market
0,2009-01-01,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN,2009-01-01,85294.39,82415.0,145046.7,130644.1,2.400000e+11,1,97.06544
1,2009-02-01,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN,2009-02-01,88213.10,84903.0,137453.7,123590.1,2.390000e+11,1,96.29944
2,2009-03-01,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN,2009-03-01,87720.89,83500.0,134329.4,120045.8,2.350000e+11,1,94.70880
3,2009-04-01,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN,2009-04-01,85022.69,81088.0,135802.4,121256.0,2.330000e+11,1,95.10927
4,2009-05-01,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN,2009-05-01,87143.64,83369.0,129079.8,116262.6,2.310000e+11,1,95.75613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,2016-02-01,02/29/2016 12:00:00 AM,713721.00,NaN,NaN,NaN,2016-02-01,121819.40,119197.0,206158.4,189556.2,2.680000e+11,1,116.46240
89,2016-03-01,03/31/2016 12:00:00 AM,612863.20,NaN,NaN,NaN,2016-03-01,121029.00,117834.0,191831.1,177132.5,2.660000e+11,1,115.76750
90,2016-06-01,06/30/2016 12:00:00 AM,676006.90,NaN,NaN,NaN,2016-06-01,120765.40,120038.0,196833.7,184675.9,2.680000e+11,1,116.91160
91,2016-09-01,09/30/2016 12:00:00 AM,747707.40,NaN,NaN,NaN,2016-09-01,124536.70,123689.0,195889.1,184249.1,2.680000e+11,1,117.17850
92,2016-08-01,08/31/2016 12:00:00 AM,798932.75,NaN,NaN,NaN,2016-08-01,124013.50,122932.0,200443.5,188376.1,2.680000e+11,1,116.67950

In [66]:
final_df.drop('Date_y',axis=1,inplace=True)

In [67]:
final_df.rename(columns={'Date_x':'Date'},inplace=True)

In [68]:
final_df

,Month-Year,Date,Monthly Total TEUs,CYTD Total TEUs,Previous Year CYTD,% Change Total TEUs CYTD,United States_export_constant_us,United States_export_current_us,United States_import_constant_us,United States_import_current_us,United States_Industry_production,United States_Exchange_rate,Retail_market
0,2009-01-01,01/31/2009 12:00:00 AM,587004.20,587004.20,NaN,NaN,85294.39,82415.0,145046.7,130644.1,2.400000e+11,1,97.06544
1,2009-02-01,02/28/2009 12:00:00 AM,413910.30,1000914.50,NaN,NaN,88213.10,84903.0,137453.7,123590.1,2.390000e+11,1,96.29944
2,2009-03-01,03/31/2009 12:00:00 AM,526487.05,1527401.55,NaN,NaN,87720.89,83500.0,134329.4,120045.8,2.350000e+11,1,94.70880
3,2009-04-01,04/30/2009 12:00:00 AM,532124.15,2059525.70,NaN,NaN,85022.69,81088.0,135802.4,121256.0,2.330000e+11,1,95.10927
4,2009-05-01,05/31/2009 12:00:00 AM,574827.80,2634353.50,NaN,NaN,87143.64,83369.0,129079.8,116262.6,2.310000e+11,1,95.75613
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,2016-02-01,02/29/2016 12:00:00 AM,713721.00,NaN,NaN,NaN,121819.40,119197.0,206158.4,189556.2,2.680000e+11,1,116.46240
89,2016-03-01,03/31/2016 12:00:00 AM,612863.20,NaN,NaN,NaN,121029.00,117834.0,191831.1,177132.5,2.660000e+11,1,115.76750
90,2016-06-01,06/30/2016 12:00:00 AM,676006.90,NaN,NaN,NaN,120765.40,120038.0,196833.7,184675.9,2.680000e+11,1,116.91160
91,2016-09-01,09/30/2016 12:00:00 AM,747707.40,NaN,NaN,NaN,124536.70,123689.0,195889.1,184249.1,2.680000e+11,1,117.17850
92,2016-08-01,08/31/2016 12:00:00 AM,798932.75,NaN,NaN,NaN,124013.50,122932.0,200443.5,188376.1,2.680000e+11,1,116.67950

In [69]:
final_df.to_excel('Maritime_data.xlsx',index=False)